# Generated by Django 3.2.6 on 2021-08-14 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agama', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Agama',
            },
        ),
        migrations.CreateModel(
            name='Citacita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'CItacita',
            },
        ),
        migrations.CreateModel(
            name='Hobi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobi', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Hobi',
            },
        ),
        migrations.CreateModel(
            name='Jeniskelamin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Jeniskelamin',
            },
        ),
        migrations.CreateModel(
            name='Pendidikanayah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendidikan_ayah', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pendidikanayah',
            },
        ),
        migrations.CreateModel(
            name='Pendidikanibu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendidikan_ibu', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pendidikanibu',
            },
        ),
        migrations.CreateModel(
            name='Pendidikanwali',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendidikan_wali', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pendidikanwali',
            },
        ),
        migrations.CreateModel(
            name='Penghasilan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penghasilan', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Penghasilan',
            },
        ),
        migrations.CreateModel(
            name='Statusasalsantri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_asal_santri', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Statusasalsantri',
            },
        ),
        migrations.CreateModel(
            name='Statushidupayah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_hidup_ayah', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Statushidupayah',
            },
        ),
        migrations.CreateModel(
            name='Statushidupibu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_hidup_ibu', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Statushidupibu',
            },
        ),
        migrations.CreateModel(
            name='Tahunpelajaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_pelajaran', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tahunpelajaran',
            },
        ),
        migrations.CreateModel(
            name='Wilayah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Wilayah',
            },
        ),
        migrations.CreateModel(
            name='Lembaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lembaga',
            },
        ),
        migrations.CreateModel(
            name='Diniyah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Diniyah',
            },
        ),
    ]
