# Generated by Django 3.2.6 on 2021-08-14 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendidikanibu',
            old_name='pendidikan_ibu',
            new_name='pendidikanibu',
        ),
    ]
