# Generated by Django 3.2.6 on 2021-08-14 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_pendidikan_ibu_pendidikanibu_pendidikanibu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendidikanibu',
            old_name='pendidikanibu',
            new_name='pendidikan_ibu',
        ),
    ]
