# Generated by Django 3.2.6 on 2021-08-14 09:39

import appsantri.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Santri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(blank=True, max_length=50, null=True)),
                ('nisn', models.CharField(blank=True, max_length=50, null=True)),
                ('nik', models.CharField(blank=True, max_length=50, null=True)),
                ('no_kk', models.CharField(blank=True, max_length=50, null=True)),
                ('nama', models.CharField(blank=True, max_length=200, null=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=50, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('alamat', models.TextField(blank=True, max_length=200, null=True)),
                ('desa', models.CharField(blank=True, max_length=30, null=True)),
                ('kecamatan', models.CharField(blank=True, max_length=30, null=True)),
                ('kabupaten', models.CharField(blank=True, max_length=30, null=True)),
                ('propinsi', models.CharField(blank=True, max_length=30, null=True)),
                ('anak_ke', models.PositiveIntegerField(blank=True, null=True)),
                ('jumlah_saudara', models.PositiveIntegerField(blank=True, null=True)),
                ('tanggal_masuk_pesantren', models.DateField(blank=True, null=True)),
                ('sekolah_asal', models.CharField(blank=True, max_length=100, null=True)),
                ('alamat_sekolah_asal', models.TextField(blank=True, max_length=100, null=True)),
                ('santri_aktif', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, default='fotokosong.gif', upload_to='foto_pics')),
                ('nama_ayah', models.CharField(blank=True, max_length=200, null=True)),
                ('nik_ayah', models.CharField(blank=True, max_length=50, null=True)),
                ('pekerjaan_ayah', models.CharField(blank=True, max_length=50, null=True)),
                ('no_hp_ayah', models.CharField(blank=True, max_length=20, null=True)),
                ('nama_ibu', models.CharField(blank=True, max_length=200, null=True)),
                ('nik_ibu', models.CharField(blank=True, max_length=50, null=True)),
                ('pekerjaan_ibu', models.CharField(blank=True, max_length=50, null=True)),
                ('no_hp_ibu', models.CharField(blank=True, max_length=20, null=True)),
                ('nama_wali', models.CharField(blank=True, max_length=200, null=True)),
                ('pekerjaan_wali', models.CharField(blank=True, max_length=50, null=True)),
                ('no_hp_wali', models.CharField(blank=True, max_length=20, null=True)),
                ('agama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.agama')),
                ('cita_cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.citacita')),
                ('diniyah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.diniyah')),
                ('hobi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.hobi')),
                ('jenis_kelamin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.jeniskelamin')),
                ('lembaga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.lembaga')),
                ('pendidikan_ayah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.pendidikanayah')),
                ('pendidikan_ibu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.pendidikanibu')),
                ('pendidikan_wali', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.pendidikanwali')),
                ('penghasilan_orang_tua_atau_wali_perbulan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.penghasilan')),
                ('status_asal_santri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.statusasalsantri')),
                ('status_hidup_ayah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.statushidupayah')),
                ('status_hidup_ibu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.statushidupibu')),
                ('tahun_pelajaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.tahunpelajaran')),
                ('wilayah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.wilayah')),
            ],
            options={
                'verbose_name_plural': 'Santri',
            },
        ),
        migrations.CreateModel(
            name='Pesan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(max_length=500, null=True)),
                ('status', django_enumfield.db.fields.EnumField(default=0, enum=appsantri.models.PesanStatus)),
                ('pesan_balasan', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diniyah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.diniyah')),
                ('lembaga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.lembaga')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('wilayah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.wilayah')),
            ],
            options={
                'verbose_name_plural': 'Pesan',
            },
        ),
    ]
